package com.app.frontend.views;

import com.app.frontend.controllers.EquiposController;
import com.app.frontend.controllers.EstadisticasController;
import com.app.frontend.controllers.MenuLateralController;
import com.app.frontend.models.Jugador;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextArea;

/**
 * Clase para la interfaz Estadisticas
 * @author Javier
 */
public class Estadisticas extends javax.swing.JFrame implements MainView{
    private Jugador jugador;
    private MenuLateral menuLateral;
    private EstadisticasController controlador;

    /**
     * Creates new form Estadisticas
     */
    public Estadisticas(Jugador jugador) {
        this.jugador = jugador;
        // Configuración del JFrame
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        // Primero inicializa los componentes Swing (importante porque si no el menu lateral no funciona)
        initComponents();
        // Configuracion del menu lateral
        this.menuLateral = new MenuLateral(); 
        new MenuLateralController(menuLateral, this);
        panelMenuLateral.setLayout(new BorderLayout());
        panelMenuLateral.add(menuLateral, BorderLayout.CENTER);

        this.controlador = new EstadisticasController(this, jugador);
    }
    
    
    public JTextArea getTextAreaEstadisticasIndividuales() {
        return textAreaEstadisticasIndividuales;
    }

    public JTextArea getTextAreaClutching() {
        return textAreaClutching;
    }

    public JTextArea getTextAreaUtilidad() {
        return textAreaUtilidad;
    }

    public JTextArea getTextAreaEstadisticasArmas() {
        return textAreaEstadisticasArmas;
    }
    
    public JTextArea getTextAreaDust2() {
        return textAreaDust2;
    }

    public JTextArea getTextAreaMirage() {
        return textAreaMirage;
    }

    public JTextArea getTextAreaNuke() {
        return textAreaNuke;
    }

    public JTextArea getTextAreaAncient() {
        return textAreaAncient;
    }

    public JTextArea getTextAreaInferno() {
        return textAreaInferno;
    }

    public JTextArea getTextAreaAnubis() {
        return textAreaAnubis;
    }

    public JTextArea getTextAreaTrain() {
        return textAreaTrain;
    }
    
    public JLabel getImagenDust2() {
        return imagenDust2;
    }

    public JLabel getImagenMirage() {
        return imagenMirage;
    }

    public JLabel getImagenNuke() {
        return imagenNuke;
    }

    public JLabel getImagenAncient() {
        return imagenAncient;
    }

    public JLabel getImagenInferno() {
        return imagenInferno;
    }

    public JLabel getImagenAnubis() {
        return imagenAnubis;
    }

    public JLabel getImagenTrain() {
        return imagenTrain;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenuLateral = new javax.swing.JPanel();
        panelInformacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelEstadisticasIndividuales = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaEstadisticasIndividuales = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        panelClutching = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaClutching = new javax.swing.JTextArea();
        panelUtilidad = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaUtilidad = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        panelArmas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAreaEstadisticasArmas = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        panelResumenJugador = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelMapas = new javax.swing.JPanel();
        panelDust2 = new javax.swing.JPanel();
        imagenDust2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        textAreaDust2 = new javax.swing.JTextArea();
        panelMirage = new javax.swing.JPanel();
        imagenMirage = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        textAreaMirage = new javax.swing.JTextArea();
        panelNuke = new javax.swing.JPanel();
        imagenNuke = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        textAreaNuke = new javax.swing.JTextArea();
        panelAncient = new javax.swing.JPanel();
        imagenAncient = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        textAreaAncient = new javax.swing.JTextArea();
        panelInferno = new javax.swing.JPanel();
        imagenInferno = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        textAreaInferno = new javax.swing.JTextArea();
        panelAnubis = new javax.swing.JPanel();
        imagenAnubis = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        textAreaAnubis = new javax.swing.JTextArea();
        panelTrain = new javax.swing.JPanel();
        imagenTrain = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        textAreaTrain = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenuLateral.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout panelMenuLateralLayout = new javax.swing.GroupLayout(panelMenuLateral);
        panelMenuLateral.setLayout(panelMenuLateralLayout);
        panelMenuLateralLayout.setHorizontalGroup(
            panelMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        panelMenuLateralLayout.setVerticalGroup(
            panelMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("Estadísticas individuales");

        panelEstadisticasIndividuales.setBackground(new java.awt.Color(204, 204, 204));

        textAreaEstadisticasIndividuales.setColumns(20);
        textAreaEstadisticasIndividuales.setRows(5);
        jScrollPane1.setViewportView(textAreaEstadisticasIndividuales);

        javax.swing.GroupLayout panelEstadisticasIndividualesLayout = new javax.swing.GroupLayout(panelEstadisticasIndividuales);
        panelEstadisticasIndividuales.setLayout(panelEstadisticasIndividualesLayout);
        panelEstadisticasIndividualesLayout.setHorizontalGroup(
            panelEstadisticasIndividualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadisticasIndividualesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEstadisticasIndividualesLayout.setVerticalGroup(
            panelEstadisticasIndividualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadisticasIndividualesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("Clutching");

        panelClutching.setBackground(new java.awt.Color(204, 204, 204));

        textAreaClutching.setColumns(20);
        textAreaClutching.setRows(5);
        jScrollPane3.setViewportView(textAreaClutching);

        javax.swing.GroupLayout panelClutchingLayout = new javax.swing.GroupLayout(panelClutching);
        panelClutching.setLayout(panelClutchingLayout);
        panelClutchingLayout.setHorizontalGroup(
            panelClutchingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClutchingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        panelClutchingLayout.setVerticalGroup(
            panelClutchingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClutchingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        panelUtilidad.setBackground(new java.awt.Color(204, 204, 204));

        textAreaUtilidad.setColumns(20);
        textAreaUtilidad.setRows(5);
        jScrollPane2.setViewportView(textAreaUtilidad);

        javax.swing.GroupLayout panelUtilidadLayout = new javax.swing.GroupLayout(panelUtilidad);
        panelUtilidad.setLayout(panelUtilidadLayout);
        panelUtilidadLayout.setHorizontalGroup(
            panelUtilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtilidadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        panelUtilidadLayout.setVerticalGroup(
            panelUtilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtilidadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jLabel3.setText("Daño de utilidad");

        panelArmas.setBackground(new java.awt.Color(204, 204, 204));

        textAreaEstadisticasArmas.setColumns(20);
        textAreaEstadisticasArmas.setRows(5);
        jScrollPane4.setViewportView(textAreaEstadisticasArmas);

        javax.swing.GroupLayout panelArmasLayout = new javax.swing.GroupLayout(panelArmas);
        panelArmas.setLayout(panelArmasLayout);
        panelArmasLayout.setHorizontalGroup(
            panelArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArmasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        panelArmasLayout.setVerticalGroup(
            panelArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArmasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setText("Estadísticas de armas distintas");

        panelResumenJugador.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Resumen estadísticas");

        javax.swing.GroupLayout panelResumenJugadorLayout = new javax.swing.GroupLayout(panelResumenJugador);
        panelResumenJugador.setLayout(panelResumenJugadorLayout);
        panelResumenJugadorLayout.setHorizontalGroup(
            panelResumenJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResumenJugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelResumenJugadorLayout.setVerticalGroup(
            panelResumenJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResumenJugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        panelMapas.setBackground(new java.awt.Color(255, 255, 255));

        imagenDust2.setText("jLabel6");

        textAreaDust2.setColumns(20);
        textAreaDust2.setRows(5);
        jScrollPane5.setViewportView(textAreaDust2);

        javax.swing.GroupLayout panelDust2Layout = new javax.swing.GroupLayout(panelDust2);
        panelDust2.setLayout(panelDust2Layout);
        panelDust2Layout.setHorizontalGroup(
            panelDust2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDust2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenDust2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        panelDust2Layout.setVerticalGroup(
            panelDust2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDust2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDust2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(imagenDust2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imagenMirage.setText("jLabel6");

        textAreaMirage.setColumns(20);
        textAreaMirage.setRows(5);
        jScrollPane6.setViewportView(textAreaMirage);

        javax.swing.GroupLayout panelMirageLayout = new javax.swing.GroupLayout(panelMirage);
        panelMirage.setLayout(panelMirageLayout);
        panelMirageLayout.setHorizontalGroup(
            panelMirageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMirageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenMirage, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMirageLayout.setVerticalGroup(
            panelMirageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMirageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMirageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenMirage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap())
        );

        imagenNuke.setText("jLabel6");

        textAreaNuke.setColumns(20);
        textAreaNuke.setRows(5);
        jScrollPane7.setViewportView(textAreaNuke);

        javax.swing.GroupLayout panelNukeLayout = new javax.swing.GroupLayout(panelNuke);
        panelNuke.setLayout(panelNukeLayout);
        panelNukeLayout.setHorizontalGroup(
            panelNukeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNukeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenNuke, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelNukeLayout.setVerticalGroup(
            panelNukeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNukeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNukeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenNuke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                .addContainerGap())
        );

        imagenAncient.setText("jLabel6");

        textAreaAncient.setColumns(20);
        textAreaAncient.setRows(5);
        jScrollPane8.setViewportView(textAreaAncient);

        javax.swing.GroupLayout panelAncientLayout = new javax.swing.GroupLayout(panelAncient);
        panelAncient.setLayout(panelAncientLayout);
        panelAncientLayout.setHorizontalGroup(
            panelAncientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAncientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenAncient, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAncientLayout.setVerticalGroup(
            panelAncientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAncientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAncientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenAncient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap())
        );

        imagenInferno.setText("jLabel6");

        textAreaInferno.setColumns(20);
        textAreaInferno.setRows(5);
        jScrollPane9.setViewportView(textAreaInferno);

        javax.swing.GroupLayout panelInfernoLayout = new javax.swing.GroupLayout(panelInferno);
        panelInferno.setLayout(panelInfernoLayout);
        panelInfernoLayout.setHorizontalGroup(
            panelInfernoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfernoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenInferno, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelInfernoLayout.setVerticalGroup(
            panelInfernoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfernoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfernoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenInferno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap())
        );

        imagenAnubis.setText("jLabel6");

        textAreaAnubis.setColumns(20);
        textAreaAnubis.setRows(5);
        jScrollPane10.setViewportView(textAreaAnubis);

        javax.swing.GroupLayout panelAnubisLayout = new javax.swing.GroupLayout(panelAnubis);
        panelAnubis.setLayout(panelAnubisLayout);
        panelAnubisLayout.setHorizontalGroup(
            panelAnubisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnubisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenAnubis, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAnubisLayout.setVerticalGroup(
            panelAnubisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnubisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAnubisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenAnubis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap())
        );

        imagenTrain.setText("jLabel6");

        textAreaTrain.setColumns(20);
        textAreaTrain.setRows(5);
        jScrollPane11.setViewportView(textAreaTrain);

        javax.swing.GroupLayout panelTrainLayout = new javax.swing.GroupLayout(panelTrain);
        panelTrain.setLayout(panelTrainLayout);
        panelTrainLayout.setHorizontalGroup(
            panelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTrainLayout.setVerticalGroup(
            panelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenTrain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel6.setText("Rendimiento por mapas");

        javax.swing.GroupLayout panelMapasLayout = new javax.swing.GroupLayout(panelMapas);
        panelMapas.setLayout(panelMapasLayout);
        panelMapasLayout.setHorizontalGroup(
            panelMapasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMapasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMapasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDust2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMirage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNuke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAncient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInferno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAnubis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTrain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMapasLayout.setVerticalGroup(
            panelMapasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMapasLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDust2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMirage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelNuke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAncient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTrain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInferno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelAnubis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelInformacionLayout = new javax.swing.GroupLayout(panelInformacion);
        panelInformacion.setLayout(panelInformacionLayout);
        panelInformacionLayout.setHorizontalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInformacionLayout.createSequentialGroup()
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelResumenJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelClutching, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelEstadisticasIndividuales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelUtilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelArmas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(panelMapas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelInformacionLayout.setVerticalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelResumenJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelEstadisticasIndividuales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelUtilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelArmas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelClutching, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(panelMapas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Jugador jugador = new Jugador();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadisticas(jugador).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagenAncient;
    private javax.swing.JLabel imagenAnubis;
    private javax.swing.JLabel imagenDust2;
    private javax.swing.JLabel imagenInferno;
    private javax.swing.JLabel imagenMirage;
    private javax.swing.JLabel imagenNuke;
    private javax.swing.JLabel imagenTrain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel panelAncient;
    private javax.swing.JPanel panelAnubis;
    private javax.swing.JPanel panelArmas;
    private javax.swing.JPanel panelClutching;
    private javax.swing.JPanel panelDust2;
    private javax.swing.JPanel panelEstadisticasIndividuales;
    private javax.swing.JPanel panelInferno;
    private javax.swing.JPanel panelInformacion;
    private javax.swing.JPanel panelMapas;
    private javax.swing.JPanel panelMenuLateral;
    private javax.swing.JPanel panelMirage;
    private javax.swing.JPanel panelNuke;
    private javax.swing.JPanel panelResumenJugador;
    private javax.swing.JPanel panelTrain;
    private javax.swing.JPanel panelUtilidad;
    private javax.swing.JTextArea textAreaAncient;
    private javax.swing.JTextArea textAreaAnubis;
    private javax.swing.JTextArea textAreaClutching;
    private javax.swing.JTextArea textAreaDust2;
    private javax.swing.JTextArea textAreaEstadisticasArmas;
    private javax.swing.JTextArea textAreaEstadisticasIndividuales;
    private javax.swing.JTextArea textAreaInferno;
    private javax.swing.JTextArea textAreaMirage;
    private javax.swing.JTextArea textAreaNuke;
    private javax.swing.JTextArea textAreaTrain;
    private javax.swing.JTextArea textAreaUtilidad;
    // End of variables declaration//GEN-END:variables

    @Override
    public Jugador getJugador() {
        return this.jugador;
    }
}
