package com.app.frontend.views;

import com.app.frontend.utils.GestionIdiomas;

/**
 * Clase de la interfaz del Menú lateral que se reutiliza en algunas interfaces
 * @author Javier
 */
public class MenuLateral extends javax.swing.JPanel {

    public MenuLateral() {
        initComponents();
    }
    
    // Métodos para asignar listeners desde el controlador
    public void setDashboardListener(java.awt.event.ActionListener listener) {
        btnDashboard.addActionListener(listener);
    }
    
    public void setEstadisticasListener(java.awt.event.ActionListener listener) {
        btnEstadisticas.addActionListener(listener);
    }
    
    public void setPartidosListener(java.awt.event.ActionListener listener) {
        btnPartidos.addActionListener(listener);
    }
    
    public void setClasificacionesListener(java.awt.event.ActionListener listener) {
        btnClasificaciones.addActionListener(listener);
    }
    
    public void setEquiposListener(java.awt.event.ActionListener listener) {
        btnEquipos.addActionListener(listener);
    }
      
    public void setBuscadorListener(java.awt.event.ActionListener listener) {
        btnBuscador.addActionListener(listener);
    }
    
    public void setCerrarListener(java.awt.event.ActionListener listener) {
        btnCerrar.addActionListener(listener);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();
        btnPartidos = new javax.swing.JButton();
        btnClasificaciones = new javax.swing.JButton();
        btnEquipos = new javax.swing.JButton();
        btnBuscador = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(204, 204, 204));

        btnDashboard.setText(GestionIdiomas.getMensaje("boton_menu_lateral_dashboard"));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnEstadisticas.setText(GestionIdiomas.getMensaje("boton_menu_lateral_estadisticas"));

        btnPartidos.setText(GestionIdiomas.getMensaje("boton_menu_lateral_partidos"));

        btnClasificaciones.setText(GestionIdiomas.getMensaje("boton_menu_lateral_clasificaciones"));
        btnClasificaciones.setMaximumSize(new java.awt.Dimension(78, 16));
        btnClasificaciones.setMinimumSize(new java.awt.Dimension(78, 16));
        btnClasificaciones.setPreferredSize(new java.awt.Dimension(78, 16));

        btnEquipos.setText(GestionIdiomas.getMensaje("boton_menu_lateral_equipos"));

        btnBuscador.setBackground(new java.awt.Color(204, 255, 204));
        btnBuscador.setText(GestionIdiomas.getMensaje("boton_menu_lateral_buscador"));

        btnCerrar.setBackground(new java.awt.Color(255, 153, 153));
        btnCerrar.setText(GestionIdiomas.getMensaje("boton_menu_lateral_cerrar"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnClasificaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(btnEstadisticas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPartidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEquipos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClasificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscador;
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnClasificaciones;
    public javax.swing.JButton btnDashboard;
    public javax.swing.JButton btnEquipos;
    public javax.swing.JButton btnEstadisticas;
    public javax.swing.JButton btnPartidos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
